### ISSUE TITLE
Blog post scoring

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#10]
As a user, I would like to receive a score from my blog post so that I can get a sense of what my current mental state is, and know how the system is evaluating me.
Acceptance criteria:
Score is calculated after posting blog post.
The app uses machine learning to classify posts as healthy and unhealthy.
Score of last post is prominently shown on homepage.
Score is available to the bot and visual representation for informing the user. 

Story source:  SRS - FR7
Estimate:  10 man-hours
Risk: High
 Value: High
Priority: H

**Comment by akohli96** [comment]
This could be medium

**Comment by akohli96** [comment]
Mark knocked this out with help of microsoft cognitive service.
