### ISSUE TITLE
Mental health visual representation

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#11]
As a user, I want a visual representation of how I am doing over time so that I can gauge how different coping mechanisms are helping me in the long run.
Acceptance criteria:
New blog post creates a new data point added to the end of the graph
Graph is visible from home page.
Graph is spaced in such a way that it is easily readable.

Story source:  SRS - FR8
Estimate:  10 man hours
Risk: Medium
 Value: Medium
Priority: L

**Comment by akohli96** [comment]
@markiragoldberg The user interaction is in[ sprint 3](https://github.com/SIU-CS/J-JAM-production/issues/19) so you dont have to worry about that if for the time being. Please throw up an emoji so I know you have read this message.

**Comment by markiragoldberg** [comment]
:+1:

**Comment by akohli96** [comment]
[We can check ](http://stackoverflow.com/questions/13352897/django-detect-mobile-device-in-views) if the graphs scale if they do not we can add something else or ask user to hop on the web.

A django app to help us : [django user agents](https://github.com/selwin/django-user_agents)
