### ISSUE TITLE
Blog page

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#12]
As a user, I want to have a page where I can see a list of my blog posts so I can reflect on my mental health.
Acceptance criteria:
There shall be a list of clickable links to all blog post titles.
User shall be able  to toggle whether a post is visible to other users or kept secret.
Secret posts shall not be visible to other users.

Story source:  SRS - FR9
Estimate:  5 man-hours
Risk: Low
 Value: High
Priority: H

**Comment by akohli96** [comment]
@pelikenesis  @markiragoldberg  progress?
