### ISSUE TITLE
Post page

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#13]
As a user, I want to be able to see and edit previous posts so that I can reflect on my mental health and affirm my self-worth through the power of positive thinking.
Acceptance criteria:
User shall be view previously made blog posts, including the title and date of post creation.
User shall be able to edit previously made blog posts.

Story source:  SRS - FR10
Estimate:  5 man-hours
Risk: Low
 Value: High
Priority: H

**Comment by akohli96** [comment]
This could be medium

**Comment by akohli96** [comment]
Done by @pelikenesis already :smiley_cat:
