### ISSUE TITLE
Making new posts

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#14]
As a user, I want to be able to make new posts from the blog page so that I can express my current state of mind, reflect upon it later, and get an assessment from the app.
Acceptance criteria:
The blog page has title and content fields, along with a submit button, to create new posts.
There is a checkbox to make the new post public, rather than secret.
Clicking the submit button gets the post onto the application.

Story source:  SRS -  FR11
Estimate:  10 man-hours
Risk: Medium
 Value: High
Priority: H

**Comment by akohli96** [comment]
@markiragoldberg @pelikenesis progress?
