### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#16]
As a user, I want to be able to go to a settings page and change my username, password, and birthday so I can restyle my online profile, keep my password secure, and make every day my birthday.
Acceptance criteria:
There shall be a settings page with fields to change username, password, and birthday.
There shall be a button to submit changes and finalize updates to this information.
User must type in password twice to make updates.

Story source:  SRS - FR13
Estimate:  10 man-hours
Risk: L
 Value: Medium
Priority: M

**Comment by akohli96** [comment]
Change username and birthday has been added here [ff03c98207cde9cb67407dacff65ea77fb3c47d7](https://github.com/SIU-CS/J-JAM-production/commit/ff03c98207cde9cb67407dacff65ea77fb3c47d7)

**Comment by akohli96** [comment]
Definitely need to make amendments on how it looks  and messages.sucess.
