### ISSUE TITLE
Bot page suggestions

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#18]
As a user, I would like the bot to make suggestions to improve my mental health, so that I can improve my mental health.
Acceptance criteria:
Posts with negative happiness scores shall trigger the bot to suggest mental health resources to compensate for the mental health.
The bot shall source mental health resources from  sources we have verified.
Happiness scores shall be calculated using the machine learning classifier.

Story source:  SRS - FR16
Estimate:  15 man-hours
Risk: M
Value: Medium
Priority: M

**Comment by akohli96** [comment]
This could also be medium

**Comment by akohli96** [comment]
@markiragoldberg 

```
<div class="container">
        <h3 class="text-center"> <a href="http://tinybuddha.com/"> Tiny Buddha</a> </h3>
    </div>

    <div class="container">
        <h3 class="text-center"> <a href="https://www.adaa.org/tips-manage-anxiety-and-stress"> Tips for managing stress </a> </h3>
    </div>

```

I ripped this off from this Ayush guys app [Positivity](https://github.com/akohli96/Positivity/blob/master/templates/index.html)
