### ISSUE TITLE
Privacy of user data

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#20]
As a user, I would like my account information to be kept private, so other users cannot see my account details.
Acceptance criteria:
Username, password, and email shall not be available publicly
Password is never displayed outside of login/registration page.
Passwords shall be stored in a secure form from which they cannot be easily extracted if bad actors acquire the password database.

Story source:  SRS - NFR2
Estimate:  5 man-hours
Risk: Low
 Value: High
Priority: H

**Comment by akohli96** [comment]
Done with #42
