### ISSUE TITLE
Application responsiveness

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#21]
As a user, I do not want to have to wait or be unable to connect while reading, editing or writing blog posts, so that I do not have to waste time when using this application.
Acceptance criteria:
The post editor responds to keyboard input within 0.01 seconds.
All pages shall be served within one second of user activity.
The bot shall respond to chat messages within 5 seconds.
The application shall be available for user access 99.9 percent of the time.

Story source:  SRS - NFR4 & NFR3 & NFR1
Estimate:  5 man hours
Risk: Low
 Value: Medium
Priority: M

**Comment by akohli96** [comment]
We will have to study how to measure this.
