### ISSUE TITLE
Post privacy

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#22]
As a user, I would like my secret posts to be kept private, so that none shall read my innermost thoughts and feelings.
Acceptance criteria:
A user’s secret posts shall not be visible to other users when others view the user’s blog page.
User login information shall be secured so that other users may not impersonate a user.
The database storing user posts shall be secured.

Story source:  SRS - NFR5
Estimate:  5 man-hours
Risk: L
 Value: High
Priority: H

**Comment by akohli96** [comment]
@pelikenesis @markiragoldberg  This will tie with Post page and blog page stories.
