### ISSUE TITLE
Tune the priorities and estimates of the product backlog

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#23]
My impression is that the priorities of the user stories are skewed too high. We currently have 3 low priorities, 5 medium priorities, and 10 high priorities. Optimism isn't bad, but we will need a clearer separation of priorities if we do wind up running into difficulties later.

Also, the time estimates of some of the stories are a little low, or at least inconsistent with the more generous time estimates of some of the others. I can adjust this without input, but I thought I should let everyone know.

I can adjust the priorities on my own before the deadline, but I would appreciate team input since setting priorities may strongly impact the outcome of our project.

**Comment by perpetual-pelican** [comment]
I think we could probably combine the blog page and post page stories. Aside from that, maybe lower the priority of the bot page suggestions and/or blog post scoring to M. If we did that, we would probably want to lower some of the affected M-priority stories to L-priority as well.

**Comment by akohli96** [comment]
I have added comments on the requirements that I think could be medium.

**Comment by akohli96** [comment]
Mark, I think its fine to go ahead and adjust the hours as you wish and then @SIU-CS/j-jam can have a look at it later

**Comment by markiragoldberg** [comment]
Ayush, I've made the changes you suggested on GitHub, tuned the time estimates slightly, and also made the bot-related stories low priority based on what we've said in person. This also roughly coincides with the sprints I've laid out.

We can revisit this if there are concerns now or later developments.
