### ISSUE TITLE
Theme and consistency

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#5]
As a user,  I would like the pages to have the same theme and be consistent, so that I can access my blog.
Acceptance criteria:
All pages have the same color scheme.
All pages have a common navigation bar.
All pages are responsive.
All pages logout from the navigation bar to the login page.

Story source:  SRS - FR1 SRS - FR15
Estimate:  5 man-hours
Risk: Low
Value: High
Priority: M

**Comment by akohli96** [comment]
@foxstrunk If you have time left after completing this story, please go ahead and make custom 400 level and 500 level pages to be displayed when  an error occurs. I think 404 and 403 should be sufficient for client side and just a general 500 level one. Thoughts @markiragoldberg @pelikenesis 

Please react with an emoji so I know everyone has seen the message :smile:

**Comment by akohli96** [comment]
This is being moved to sprint 3 since it is not fully implemented here.
