### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#6]
As a user,  I would like to be able to login, so that I can safely and privately access my blog.
Acceptance criteria:
Can login through Google or Facebook or email.
Application should block user from logging in after 3 failures for 1 minute.
Application should ask for captcha afterwards.
Login shall take the user to the home page.

Story source:  SRS - FR2   SRS - FR15
Estimate:  6 man-hours
Risk: Low
Value: High
Priority: H

**Comment by akohli96** [comment]
Can login through Google or email or twitter.
Need to do recaptcha and failure. 

[Reference](http://stackoverflow.com/questions/9033287/lock-out-users-after-too-many-failed-login-attempts)

**Comment by akohli96** [comment]
Done with #42
