### ISSUE TITLE
Registration details

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#7]
As a user,  I would like to be able to register without using a different service’s account, so that I can safely and privately login and access my blog with unique credentials.
Acceptance criteria:
The registration shall fail if the username is not unique.
The registration shall fail if not all fields are correctly filled.
Registration shall require validating the email address through an email to the address.

Story source:  SRS - FR3
Estimate:  8 man-hours
Risk: Low
 Value: High
Priority: H

**Comment by akohli96** [comment]
User can register and can validate email address, Need to study data sync and pipelines later.

**Comment by akohli96** [comment]
Done with #41
