### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#8]
As a user, I would like to reset my password, so I can securely unlock my account when I forget my password.
Acceptance criteria:
There shall be a forgot password link that sends a reset email to the desired user.
The app shall require the user creates a new password after resetting the password and logging in.
The reset email link shall expire after 48 hours to keep it secure.

Story source:  SRS - FR4
Estimate:  10 man-hours
Risk: Medium
 Value: High
Priority: H

**Comment by akohli96** [comment]
Almost done. IDK about the reset expire link. Will need to dig a little further in docs but there is a reset link.

**Comment by akohli96** [comment]
[Password reset setting ](https://github.com/SIU-CS/J-JAM-production/commit/a1ef0e4043cc602cdf4bde0e7ee3638db65a00f0) commited change.
