### ISSUE TITLE
Homepage description

### ISSUE THREAD

**Issue by markiragoldberg** [SIU-CS/J-JAM-production#9]
As a user, I would like to see an inspirational quote and a summary of my mental health so that I can maintain and improve my mental health.
Acceptance criteria:
The inspirational quote should change every 24 hours.
There should be a summary of the last post.
The quote shall be sourced from an API providing positive quotes.

Story source:  SRS - FR6
Estimate:  10 man-hours
Risk: Medium
 Value: High
Priority: M

**Comment by akohli96** [comment]
[API schedule](http://stackoverflow.com/questions/573618/django-set-up-a-scheduled-job) This would be the easiest way of getting api issue done.

More helper links : [JS vs meta refresh](http://stackoverflow.com/questions/14125661/javascript-page-reload-or-meta-tag-refresh-method)

**Comment by akohli96** [comment]
Almost there  , need  to do meta refresh and integrate django crontab

 But [have done quote api getting and django command](https://github.com/SIU-CS/J-JAM-production/commit/00c092572cdfa4d744f1e9d9c8d6ed981728edfa)
